services:
  db:
    image: postgres:latest
    container_name: post_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"

  web:
    image: ${DOCKER_USERNAME}/postapp:latest
    container_name: post_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./logs:/logs
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  postgres_data:
